(ns learn.client.mutations
  "Phase 12.7 — Fulcro defmutations extracted from `learn.client`.

   Each `defmutation` here uses an explicit fully-qualified target
   symbol (e.g. `learn.client/add-todo`). Fulcro's macro detects that
   the supplied symbol already carries a namespace and registers the
   `mutate` multimethod under THAT wire sym instead of synthesising
   one from the current namespace. This preserves the server-side
   dispatch contract — `learn.resolvers` references
   `'learn.client/add-todo` and friends in `::pc/sym` — without any
   wire-protocol rename.

   Because the wire sym already had a namespace, the Fulcro macro
   skips creating a `def` for the Mutation record in this namespace.
   The UI layer (which calls e.g. `(comp/transact! [(add-todo {…})])`)
   needs callable vars to live SOMEWHERE; those are declared back in
   `learn.client` via `m/declare-mutation`, which is a pure alias and
   keeps `learn.client/add-todo` resolvable for tests and call sites.

   Helpers depend on `learn.client.state/*` (the pure state-map helpers)
   and `learn.util.normalized` (for `remote-list-items`). The CLJS-only
   `url-encoding/replace-url-with-items!` call in `keep-local-list`
   stays guarded by reader conditional — `url-encoding` is required
   unconditionally because the namespace is `.cljc` and only the one
   function is CLJS-only."
  (:require
    [com.fulcrologic.fulcro.mutations :as m :refer [defmutation]]
    [learn.client.state :as state]
    [learn.util.normalized :as norm]
    [learn.util.url-encoding :as url-encoding]))

;; ============================================================================
;; Remote helper
;; ============================================================================

(defn- remote-list-items
  "Builds a remote AST whose params carry the current denormalized list
   at [:list/id 1] as `:list/items`. Server mutations write this vector
   straight to SERVER-DB."
  [env]
  (let [items (norm/denormalize-list-items @(:state env) [:list/id 1])]
    (m/with-params env {:list/items items})))

;; ============================================================================
;; List mutations
;; ============================================================================

(defmutation learn.client/add-todo [{:todo/keys [text]}]
  (action [{:keys [state ref]}]
    (swap! state state/add-todo* ref text))
  (remote [env] (remote-list-items env)))

(defmutation learn.client/delete-all [_]
  (action [{:keys [state ref]}]
    (swap! state state/delete-all* ref))
  ;; Phase 7.3: enable server sync so localStorage persistence reflects
  ;; the empty list after the user clicks Delete List. Server has a
  ;; matching `learn.client/delete-all` Pathom mutation.
  (remote [env] (remote-list-items env)))

(defmutation learn.client/import-from-text
  "Phase 7.12 — batch import from the save modal textarea. Splits the
   given text on newlines, drops blank lines, and appends each as a
   fresh todo following `add-todo`'s status rule. No-op when the model
   refuses (all-blank input)."
  [{:ui/keys [textarea-import-text]}]
  (action [{:keys [state ref]}]
    (swap! state state/import-from-text* ref textarea-import-text))
  (remote [env] (remote-list-items env)))

(defmutation learn.client/import-from-json
  "Phase 13 — JSON-file batch import. UI calls
   `tasks-io/parse-tasks-json` on the uploaded file content; on
   success it dispatches this mutation with the already-parsed
   items. Statuses preserved verbatim (no auto-mark applied); fresh
   UUIDs were generated by `og-shape->items` during parse so we
   never collide with existing entities."
  [{:keys [items]}]
  (action [{:keys [state ref]}]
    (swap! state state/import-from-json* ref items))
  (remote [env] (remote-list-items env)))

(defmutation learn.client/keep-link-list
  "Phase 7.18 — user resolved the conflict modal by picking the URL
   list. Replace normalized state with the stashed URL items, then
   close the modal. The URL bar already reflects URL items (the user
   came via that URL); `install-url-sync!` will idempotently re-write
   it on the items-change anyway."
  [_]
  (action [{:keys [state ref]}]
    (swap! state state/keep-link-list* ref))
  (remote [env] (remote-list-items env)))

(defmutation learn.client/keep-local-list
  "Phase 7.18 — user resolved the conflict modal by keeping the
   localStorage list. State already holds those items; this is just
   close-the-modal + clear-the-stash + force the URL bar to reflect
   the local items (without an items change, `install-url-sync!`'s
   watch wouldn't fire — see its docstring)."
  [_]
  (action [{:keys [state ref]}]
    (swap! state state/keep-local-list* ref)
    #?(:cljs
       (let [items (norm/denormalize-list-items @state ref)]
         (url-encoding/replace-url-with-items! items)))))

(defmutation learn.client/set-status [{:todo/keys [id status]}]
  (action [{:keys [state]}]
    (swap! state state/set-status* id status))
  #_(remote [_] true)               ; no server handler (admin/REPL-only)
  )

;; List-ident is hardcoded `[:list/id 1]` for the current singleton-list
;; design; revisit when multi-list support arrives.
(defmutation learn.client/cancel-todo [{:todo/keys [id]}]
  (action [{:keys [state]}]
    (swap! state state/cancel-todo* [:list/id 1] id))
  (remote [env] (remote-list-items env)))

(defmutation learn.client/complete-benchmark-item [_]
  (action [{:keys [state]}]
    (swap! state state/complete-benchmark-item* [:list/id 1]))
  (remote [env] (remote-list-items env)))

(defmutation learn.client/clone-todo [{:todo/keys [id]}]
  (action [{:keys [state]}]
    (swap! state state/clone-todo* [:list/id 1] id))
  (remote [env] (remote-list-items env)))

;; Phase 7.4 — modal state mutations. Local-only (no server sync) since
;; modal open/close is pure UI state. Hardcoded list-ident `[:list/id 1]`
;; matches the singleton pattern used by the rest of the file.
(defmutation learn.client/set-open-modal [{:ui/keys [open-modal]}]
  (action [{:keys [state]}]
    (swap! state state/set-open-modal* [:list/id 1] open-modal)))

(defmutation learn.client/toggle-open-modal [{:ui/keys [open-modal]}]
  (action [{:keys [state]}]
    (swap! state state/toggle-open-modal* [:list/id 1] open-modal)))

(defmutation learn.client/toggle-theme [_]
  (action [{:keys [state]}]
    (swap! state state/toggle-theme* [:list/id 1])))

;; Phase 12.5 — set the i18n locale. Client-only: locale lives in
;; `:ui/locale` which is in `storage/ui-prefs-whitelist`, so the
;; storage watch persists it; the server never sees it.
(defmutation learn.client/set-locale [{:ui/keys [locale]}]
  (action [{:keys [state]}]
    (swap! state state/set-locale* [:list/id 1] locale)))

;; Phase 7.9: page-level error setter. `nil` clears, string sets.
(defmutation learn.client/set-err-msg [{:ui/keys [err-msg]}]
  (action [{:keys [state]}]
    (swap! state state/set-err-msg* [:list/id 1] err-msg)))

;; Remote-only mutation fired from the review chart's :yes action. The
;; chart has already mutated the client state-map via `ops/assign`; this
;; defmutation has no `(action ...)` body because there's no client work
;; left to do. Its `(remote ...)` ships the post-action items vector to
;; the server's `sync-list` mutation.
(defmutation learn.client/sync-list [_]
  (remote [env] (remote-list-items env)))
